apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  app.kubernetes.io/part-of: argocd
generatorOptions:
  disableNameSuffixHash: true

resources:
  - manifests/namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml
  - manifests/ingress.yml

generators:
  - config/argocd-secret.yml
  - config/secret-gpg-keys.yml
  - config/argocd-repo-creds.yml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    path: manifests/argocd-server-insecure.patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    path: manifests/repo-server-kustomize-pass.patch.yml

images:
  - name: quay.io/argoproj/argocd
    newName: ghcr.io/ftsell/argocd-kustomize-pass

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    envs:
      - config/argocd.env
    files:
      - dex.config=config/argocd.dex.yml

  - name: argocd-rbac-cm
    behavior: merge
    envs:
      - config/rbac.env
    files:
      - policy.csv=config/rbac.policy.csv

