# replace the existing gpg-keys volume definition to include secret gpg keys as well
- op: replace
  path: /spec/template/spec/volumes/2
  value:
    name: gpg-keys
    projected:
      sources:
        - secret:
            name: argocd-gpg-secret-keys
        - configMap:
            name: argocd-gpg-keys-cm


# set environment variables so that kustomize-pass can correctly interact with secret repositories
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: XDG_DATA_HOME
    value: /tmp/data
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GNUPGHOME
    value: /app/config/gpg/keys

# Set imgepullpolicy to IfNotPresent
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: IfNotPresent